### ISSUE TITLE
This place is a bit hard to find. Possible to add upload direct from the Vita?

### ISSUE THREAD

**Issue by ghost** [ONElua/VitaBubbles#12]
I made some prince of persia bubbles but have no idea how to add them here. 

Here's the link: https://drive.google.com/drive/folders/1rZzl8naQFcVQc9qig3yPN6C6hTkYBi8w?usp=sharing

There also appear to be a large number (hundreds) of bubbles on reddit, but since its hard or people don't even know about the online feature, they just leave them on reddit. Here's some links:

https://www.reddit.com/r/vitahacks/comments/93t3k8/sharing_bubble_arts_that_ive_made_for_use_with/

https://www.reddit.com/r/vitahacks/comments/gk33ly/my_psxpsp_official_art_faces_bubbles/

https://www.reddit.com/r/vitahacks/comments/do0a2a/the_ultimate_psp_abm_bubbles_pack_is_here_170/

https://www.reddit.com/r/vitahacks/comments/gf9hoq/i_made_some_psp_and_psx_custom_bubbles_for_abm/

**Comment by takuhii** [comment]
If you like I can add them for you :)

I'm not an admin, but you need to know Github, and create a fork/branch of this repo and then add your files to that, then create a pull-request for the admin to approve... Your images won't be available until they are approved though...

**Comment by ghost** [comment]
No thank you, someone already did it for my fails. Just wanted to share the files of other creators from reddit. Hopefully they can be added too.

**Comment by takuhii** [comment]
Ah that's ok then. Just wondered. Looking at your files though the sizes
are slightly out for some images, and the template.xml is missing. Also the
thumbnails are named wrong, they should match the name you gave the zip
file :)

**Comment by ghost** [comment]
Thanks. I removed the thumbnails from the zips and renamed them to the ID. Should look fine now. 

Is the template.xml even needed? I was able to change my bubbles without it and everything went smoothly.

**Comment by takuhii** [comment]
The thumbnails name should match the name of the folder with the images in.

No worries, I'll leave your files be ;)
