### ISSUE TITLE
New Repo?

### ISSUE THREAD

**Issue by takuhii** [ONElua/VitaBubbles#15]
OK, so I cloned your repo into GitLab, it's publically viewable at the moment, the download URLs look like this;
https://gitlab.com/onelua/vitabubbles/-/raw/master/2XEXTREMEPS1RETRO.jpg?inline=false

The repo itself is here;
https://gitlab.com/onelua/vitabubbles/-/tree/master

I forked your ABM repo as well and changed a few resources as a test...
https://github.com/takuhii/AdrenalineBubbleManager/blob/master/AdrenalineBubbleManager/system/

Not sure how I go about building it...

**Please be aware I have created a ONELua GROUP under my account, I have not registered as ONELUA, it just makes it easier to manage users...**

**Comment by takuhii** [comment]
Please take a look and see what you think...

**Comment by ONElua** [comment]
http.getfile('https://gitlab.com/onelua/vitabubbles/-/tree/master/'..entry.id..".jpg?inline=false", PATH_COVERS.."tmpcover.jpg"))

have you already downloaded?from ABM?

**Comment by takuhii** [comment]
Not sure what you mean, I cloned the repo from GitHub to GitLab, and tried
changing the URLs that pointed to remote jpg or zips...

I'm not this type of developer, so this is all new to me.

**Comment by ONElua** [comment]
No problem
For now I do not have internet 
but as soon as I have a time I make all the necessary changes

I can be more in communication at gdljjrod @ gmail.com

**Comment by ONElua** [comment]
We have a problem, in the downloads you have to log in
That's not good for direct downloads

**Comment by takuhii** [comment]
I'll look into it and get back to you ;)

**Comment by ONElua** [comment]
Takuhii
Please upload the resources from capSilver
Missing: GOWCHAINSOLYMPUS.jpg
Missing: GOWCHAINSOLYMPUS.zip
Missing: capSilver

Missing: GOWGHOSTSPARTA.jpg
Missing: GOWGHOSTSPARTA.zip
Missing: capSilver

Missing: GKHISTORY.jpg
Missing: GKHISTORY.zip
Missing: capSilver

Missing: GTACHINATOWNWARS.jpg
Missing: GTACHINATOWNWARS.zip
Missing: capSilver

Missing: GTALIBERTYCITYSTORIES.jpg
Missing: GTALIBERTYCITYSTORIES.zip
Missing: capSilver

Missing: GTAVICECITYSTORIES.jpg
Missing: GTAVICECITYSTORIES.zip
Missing: capSilver

Missing: GROWLANCERWOT.jpg
Missing: GROWLANCERWOT.zip
Missing: capSilver

Missing: GUNSHOWDOWN.jpg
Missing: GUNSHOWDOWN.zip
Missing: capSilver

Missing: GURUMINMA.jpg
Missing: GURUMINMA.zip
Missing: capSilver

Missing: HALFMINUTEHEROCS.jpg
Missing: HALFMINUTEHEROCS.zip
Missing: capSilver

Missing: HALFMINUTEHERO2.jpg
Missing: HALFMINUTEHERO2.zip
Missing: capSilver

Missing: HEXYSFORCE.jpg
Missing: HEXYSFORCE.zip
Missing: capSilver

Missing: JEANNEDARC.jpg
Missing: JEANNEDARC.zip
Missing: capSilver

Missing: JUICED2.jpg
Missing: JUICED2.zip
Missing: capSilver

Missing: KILLZONELIBERATION.jpg
Missing: KILLZONELIBERATION.zip
Missing: capSilver

Missing: KHBBS.jpg
Missing: KHBBS.zip
Missing: capSilver

Missing: KINGDOMOFPARADISE.jpg
Missing: KINGDOMOFPARADISE.zip
Missing: capSilver

Missing: LEGOSTARWARSORIGINALTRILOGY.jpg
Missing: LEGOSTARWARSORIGINALTRILOGY.zip
Missing: capSilver

Missing: LITTLEBIGPLANET.jpg
Missing: LITTLEBIGPLANET.zip
Missing: capSilver

Missing: LOCOROCO1.jpg
Missing: LOCOROCO1.zip
Missing: capSilver

Missing: LOCOROCO2CS.jpg
Missing: LOCOROCO2CS.zip
Missing: capSilver

Missing: MANHUNT2.jpg
Missing: MANHUNT2.zip
Missing: capSilver

Missing: MARVELULTIMATEALLIANCE.jpg
Missing: MARVELULTIMATEALLIANCE.zip
Missing: capSilver

Missing: MEMYKATAMARI.jpg
Missing: MEMYKATAMARI.zip
Missing: capSilver

Missing: MEDIEVILRESSURECTION.jpg
Missing: MEDIEVILRESSURECTION.zip
Missing: capSilver

Missing: PATAPONCS2.jpg
Missing: PATAPONCS2.zip
Missing: capSilver

Missing: PATAPONCS3.jpg
Missing: PATAPONCS3.zip
Missing: capSilver


![MacosX](https://user-images.githubusercontent.com/25811032/86364766-37e57400-bc3e-11ea-9b66-04f8ed6509fc.png)

**Comment by takuhii** [comment]
Added to my PR... Should be good to go ;)

**Comment by ONElua** [comment]
yes
make new pull
Thanks

PD: I uploaded capture where I show macOS files
in your zips

**Comment by takuhii** [comment]
It's because I just right click and compress from FINDER... Let me see what I can do ;)

**Comment by takuhii** [comment]
PR created ;)

**Comment by ONElua** [comment]
ok my email is gdljjrod @ gmail.com and twitter/gdljjrod
