### ISSUE TITLE
Resources by sciascillo

### ISSUE THREAD

**Issue by sciascillo** [ONElua/VitaBubbles#8]
I don't know how to upload my resource so
![HERCSADRETRO](https://user-images.githubusercontent.com/13934136/72443547-bb092f80-37ae-11ea-9a1a-5838987570d4.jpg)
[HERCSADRETRO.zip](https://github.com/ONElua/VitaBubbles/files/4065431/HERCSADRETRO.zip)

**Comment by ONElua** [comment]
ok
im upload
thanks
