### ISSUE TITLE
Template.xml?

### ISSUE THREAD

**Issue by takuhii** [ONElua/VitaBubbles#9]
Hi,
What is the template.xml actually for? Could you explain please, also, how do we structure it, what's supposed to be in it?

Many thanks
Darren

**Comment by takuhii** [comment]
So I figured it out... The template.xml should look like this;

`<?xml version="1.0" encoding="utf-8"?>`
`<livearea style="a5" format-ver="01.00" content-rev="1">`
`    <livearea-background>`
`        <image>bg0.png</image>`
`    </livearea-background>`
`    <gate>`
`        <startup-image>startup.png</startup-image>`
`    </gate>`
`</livearea>`

**Comment by ONElua** [comment]
Yes.
https://playstationdev.wiki/psvitadevwiki/index.php?title=Template.xml

We take bg0.png or bg.png for livearea-background

**Comment by takuhii** [comment]
Thanks for clearing that up. Could you merge my pull request if it is ok please?

**Comment by ONElua** [comment]
https://www.reddit.com/r/vitahacks/comments/hjmn5k/ps_vita_daedalusx64_and_retroarch_custom_bubbles/
more example Template
